encourage_to_update_profile: Keeping your profile up to date helps leaders determine if you are physically fit for a particular event. Your profile information is visible only to the leaders of the events you register for. 
